server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhipu_chat_room?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:mapperxml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
ZhiPu:
  apiKey: "9ecb14421c67429f85336336fb05db58.d2AKYFXGG2Nq5dzO"
  imageUrl: "https://open.bigmodel.cn/api/paas/v4/images/generations"
  messageUrl: "https://open.bigmodel.cn/api/paas/v4/chat/completions"
  videoUrl: "https://open.bigmodel.cn/api/paas/v4/videos/generations"
  getVideoUrl: "https://open.bigmodel.cn/api/paas/v4/async-result/"
  imageModel: "cogview-4-250304"
  messageModel: "glm-4v-plus"
  videoModel: "cogvideox-2"